[build]
exclude = [
    "/README.md",
]

  [[build.buildpacks]]
  uri = "paketo-buildpacks/php-httpd"

  [[build.buildpacks]]
  uri = "paketo-buildpacks/php"

  [[ build.env ]]
    name="BP_NODE_RUN_SCRIPTS"
    value="build"

  [[ build.env ]]
    name="BP_WEB_SERVER"
    value="php-httpd"

  [[ build.env ]]
    name="BP_WEB_SERVER_ROOT"
    value="dist"

  [[ build.env ]]
    name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
    value="true"
